global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Monitor itself

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
