global:
  scrape_interval: 5s # How often to scrape targets by default.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Monitor itself

  - job_name: "myapp"
    static_configs:
      - targets: ["localhost:8088"]
