services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    network_mode: host

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.10.0
  #   ports:
  #     - "5044:5044" 
  #     - "9600:9600"
  #     - "5000:5000"
  #   network_mode: host
  #   depends_on:
  #     - elasticsearch
  #   volumes:
  #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200
    network_mode: host
