services:
  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # prometheus config
      - ./docker:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host

  grafana:
    image: grafana/grafana
    user: root
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/data:/var/lib/grafana # to ensure grafana data won't gone if container restarted
    network_mode: host