global:
  scrape_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app_type: tools
          app_name: prometheus
    scrape_interval: 1s

  - job_name: "golang_app"
    static_configs:
      - targets: ["localhost:9001"]
        labels:
          app_type: http_server
          app_name: microservice